fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
    registry:
      repo: 'https://github.com/puppetlabs/puppetlabs-registry.git'
      ref: '1.0.0'
  symlinks:
    windows_autoupdate: "#{source_dir}"
